name: Run Jest Test
on: 
 push: 
  branches-ignore:
  - "master"
  - "github-action/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test