name: Run Jest Test
on: 
 push: 
  branches-ignore:
  - "master"
  - "github-action/**"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v2
    - uses: c-hive/gha-yarn-cache@v2
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test